//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEcommerceAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Piece
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> DateCommande { get; set; }
        public Nullable<int> NumCommande { get; set; }
        public Nullable<int> IdFacture { get; set; }
    
        public virtual Client Client { get; set; }
    }
}
