//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEcommerceAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionProduit
    {
        public int PromotionID { get; set; }
        public int ProduitsID { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateExpidite { get; set; }
    
        public virtual Promotion Promotion { get; set; }
        public virtual Produits Produits { get; set; }
    }
}
